package com.ecom.catalog.domain;

import jakarta.persistence.*;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.UUID;

/**
 * Maps to {@code users} table.
 *
 * <p>Design notes:</p>
 * <ul>
 *   <li>{@code id} is the internal BIGSERIAL — used for FK joins, never exposed in API.</li>
 *   <li>{@code publicId} is UUID v7 (DB-generated by default). Exposed in API as the
 *       public identifier (URLs, JWT {@code sub}).</li>
 *   <li>{@code email} maps to PG {@code CITEXT} (case-insensitive). String works fine
 *       on the Java side — PG compares case-insensitively.</li>
 *   <li>{@code passwordHash} is BCrypt; never expose it.</li>
 *   <li>{@code version} drives JPA optimistic locking.</li>
 *   <li>{@code createdAt} / {@code updatedAt} are DB-managed (defaults + trigger).
 *       We mark them {@code insertable=false, updatable=false} so JPA doesn't touch.</li>
 * </ul>
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @JdbcTypeCode(SqlTypes.UUID)
    @Column(name = "public_id", insertable = false, updatable = false)
    private UUID publicId;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(name = "email_verified", nullable = false)
    private boolean emailVerified = false;

    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    @Column(name = "full_name", nullable = false)
    private String fullName;

    @Column
    private String phone;

    @Column(name = "avatar_url")
    private String avatarUrl;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserStatus status = UserStatus.ACTIVE;

    @Column(name = "last_login_at")
    private Instant lastLoginAt;

    @Column(name = "created_at", insertable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "updated_at", insertable = false, updatable = false)
    private Instant updatedAt;

    @Column(name = "created_by")
    private Long createdBy;

    @Column(name = "updated_by")
    private Long updatedBy;

    @Version
    @Column(nullable = false)
    private Long version;

    @Column(name = "deleted_at")
    private Instant deletedAt;

    // ─── Convenience constructor for registration ────────────────────────
    public static User newCustomer(String email, String passwordHash, String fullName, String phone) {
        User u = new User();
        u.email = email.toLowerCase();
        u.passwordHash = passwordHash;
        u.fullName = fullName;
        u.phone = phone;
        u.status = UserStatus.ACTIVE;
        u.emailVerified = false;
        return u;
    }

    public boolean isActive() {
        return status == UserStatus.ACTIVE && deletedAt == null;
    }
}
